---
# Build configuration for PV Forecast Comparison add-on
name: "PV Forecast Comparison"
slug: "pv_forecast_comparison"
description: "Compare PV production forecasts with actual production data"
version: "1.0.0"
url: "https://github.com/seppkurt/pv-forecast-comparison-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8123/tcp: 8123
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw 