name: "PV Forecast Comparison"
version: "1.0.0"
slug: "pv_forecast_comparison"
description: "Compare PV production forecasts with actual production data"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8123/tcp: 8123
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw
options:
  ha_url: "http://supervisor/core"
  ha_token: ""
  forecast_entities:
    - "sensor.pv_production_forecast"
    - "sensor.solar_forecast"
    - "sensor.pv_forecast"
    - "sensor.solar_production_forecast"
  production_entities:
    - "sensor.pv_power"
    - "sensor.solar_power"
    - "sensor.pv_production"
    - "sensor.solar_production"
  daily_entities:
    - "sensor.pv_daily_energy"
    - "sensor.solar_daily_energy"
    - "sensor.pv_today_energy"
    - "sensor.solar_today_energy"
  collection_times:
    4am: "04:00:00"
    11am: "11:00:00"
    3pm: "15:00:00"
    11pm: "23:00:00"
  log_level: "INFO"
schema:
  ha_url: str
  ha_token: str
  forecast_entities: list
  production_entities: list
  daily_entities: list
  collection_times: dict
  log_level: str 